#This is just a file containing some words for importation to other codes

english_words = [
    "apple", "banana", "orange", "grape", "melon",
    "cherry", "strawberry", "blueberry", "kiwi", "mango",
    "cat", "dog", "elephant", "lion", "tiger",
    "fish", "shark", "dolphin", "whale", "penguin",
    "house", "apartment", "cottage", "villa", "castle",
    "car", "bike", "train", "plane", "boat",
    "red", "blue", "green", "yellow", "purple",
    "happy", "sad", "angry", "excited", "bored",
    "run", "walk", "jump", "swim", "fly",
    "book", "pen", "notebook", "computer", "phone"
]


celebrity_data = [
    {
        'name': 'Cristiano Ronaldo',
        'followers': 663,
        'description': 'Footballer',
        'country': 'Portugal',
    },
    {
        'name': 'Lionel Messi',
        'followers': 506,
        'description': 'Footballer',
        'country': 'Argentina',
    },
    {
        'name': 'Selena Gomez',
        'followers': 417,
        'description': 'Musician & Actress',
        'country': 'United States',
    },
    {
        'name': 'Kylie Jenner',
        'followers': 392,
        'description': 'Media personality & Businesswoman',
        'country': 'United States',
    },
    {
        'name': 'Dwayne Johnson',
        'followers': 392,
        'description': 'Actor & Wrestler',
        'country': 'United States',
    },
    {
        'name': 'Ariana Grande',
        'followers': 374,
        'description': 'Musician & Actress',
        'country': 'United States',
    },
    {
        'name': 'Kim Kardashian',
        'followers': 355,
        'description': 'Media personality & Businesswoman',
        'country': 'United States',
    },
    {
        'name': 'Beyoncé',
        'followers': 310,
        'description': 'Musician & Actress',
        'country': 'United States',
    },
    {
        'name': 'Khloé Kardashian',
        'followers': 301,
        'description': 'Media personality',
        'country': 'United States',
    },
    {
        'name': 'Justin Bieber',
        'followers': 294,
        'description': 'Musician',
        'country': 'Canada',
    },
    {
        'name': 'Kendall Jenner',
        'followers': 286,
        'description': 'Media personality & Model',
        'country': 'United States',
    },
    {
        'name': 'Taylor Swift',
        'followers': 282,
        'description': 'Musician',
        'country': 'United States',
    },
    {
        'name': 'Virat Kohli',
        'followers': 273,
        'description': 'Cricketer',
        'country': 'India',
    },
    {
        'name': 'Jennifer Lopez',
        'followers': 248,
        'description': 'Musician & Actress',
        'country': 'United States',
    },
    {
        'name': 'Neymar',
        'followers': 231,
        'description': 'Footballer',
        'country': 'Brazil',
    },
    {
        'name': 'Nicki Minaj',
        'followers': 224,
        'description': 'Musician',
        'country': 'Trinidad & Tobago / United States',
    },
    {
        'name': 'Kourtney Kardashian',
        'followers': 217,
        'description': 'Media personality',
        'country': 'United States',
    },
    {
        'name': 'Miley Cyrus',
        'followers': 212,
        'description': 'Musician & Actress',
        'country': 'United States',
    },
    {
        'name': 'Katy Perry',
        'followers': 203,
        'description': 'Musician',
        'country': 'United States',
    },
    {
        'name': 'Zendaya',
        'followers': 177,
        'description': 'Actress & Singer',
        'country': 'United States',
    },
    {
        'name': 'Kevin Hart',
        'followers': 176,
        'description': 'Comedian & Actor',
        'country': 'United States',
    },
    {
        'name': 'Cardi B',
        'followers': 163,
        'description': 'Musician & Actress',
        'country': 'United States',
    },
    {
        'name': 'LeBron James',
        'followers': 158,
        'description': 'Basketball Player',
        'country': 'United States',
    },
    {
        'name': 'Demi Lovato',
        'followers': 153,
        'description': 'Musician & Actress',
        'country': 'United States',
    },
    {
        'name': 'Rihanna',
        'followers': 149,
        'description': 'Musician & Businesswoman',
        'country': 'Barbados',
    },
    {
        'name': 'Chris Brown',
        'followers': 144,
        'description': 'Musician',
        'country': 'United States',
    },
    {
        'name': 'Drake',
        'followers': 142,
        'description': 'Musician',
        'country': 'Canada',
    },
    {
        'name': 'Ellen DeGeneres',
        'followers': 135,
        'description': 'Comedian & TV Host',
        'country': 'United States',
    },
    {
        'name': 'Kylian Mbappé',
        'followers': 125,
        'description': 'Footballer',
        'country': 'France',
    },
    {
        'name': 'Billie Eilish',
        'followers': 124,
        'description': 'Musician',
        'country': 'United States',
    },
    {
        'name': 'Gal Gadot',
        'followers': 107,
        'description': 'Actress',
        'country': 'Israel',
    },
    {
        'name': 'Lisa (Lalisa Manoban)',
        'followers': 106,
        'description': 'Musician (BLACKPINK)',
        'country': 'Thailand',
    },
    {
        'name': 'Vin Diesel',
        'followers': 103,
        'description': 'Actor',
        'country': 'United States',
    },
    {
        'name': 'Shraddha Kapoor',
        'followers': 93.9,
        'description': 'Actress',
        'country': 'India',
    },
    {
        'name': 'Shakira',
        'followers': 93.1,
        'description': 'Musician',
        'country': 'Colombia',
    },
    {
        'name': 'Priyanka Chopra Jonas',
        'followers': 92.5,
        'description': 'Actress',
        'country': 'India',
    },
    {
        'name': 'Snoop Dogg',
        'followers': 88.5,
        'description': 'Musician',
        'country': 'United States',
    },
    {
        'name': 'David Beckham',
        'followers': 88.2,
        'description': 'Former Footballer',
        'country': 'United Kingdom',
    },
    {
        'name': 'Jennie (Jennie Kim)',
        'followers': 88.1,
        'description': 'Musician (BLACKPINK)',
        'country': 'South Korea',
    },
    {
        'name': 'Dua Lipa',
        'followers': 88.0,
        'description': 'Musician',
        'country': 'United Kingdom',
    },
    {
        'name': 'Alia Bhatt',
        'followers': 86.5,
        'description': 'Actress',
        'country': 'India',
    },
    {
        'name': 'Davido',
        'followers': 30.7,
        'description': 'Musician',
        'country': 'Nigeria',
    },
    {
        'name': 'Wizkid',
        'followers': 19.1,
        'description': 'Musician',
        'country': 'Nigeria',
    },
    {
        'name': 'Tiwa Savage',
        'followers': 19.5,
        'description': 'Musician',
        'country': 'Nigeria',
    },
    {
        'name': 'Burna Boy',
        'followers': 17.6,
        'description': 'Musician',
        'country': 'Nigeria',
    },
    {
        'name': 'Funke Akindele',
        'followers': 17.7,
        'description': 'Actress & Filmmaker',
        'country': 'Nigeria',
    },
    {
        'name': 'Yemi Alade',
        'followers': 17.3,
        'description': 'Musician',
        'country': 'Nigeria',
    },
    {
        'name': 'Don Jazzy',
        'followers': 15.0,
        'description': 'Music Producer',
        'country': 'Nigeria',
    },
    {
        'name': 'Mercy Johnson Okojie',
        'followers': 14.8,
        'description': 'Actress',
        'country': 'Nigeria',
    },
    {
        'name': 'Blackpink (Group Official)',
        'followers': 55.9,
        'description': 'Musicians (K-pop group)',
        'country': 'South Korea',
    },
]
